### ISSUE TITLE
Nutritional info format

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#13]
We need nutritional info with display strings and units

**Comment by jonathankeebler** [comment]
TBD: Only put that info in separate /item call or in main call too?

**Comment by jonathankeebler** [comment]
Added a more in-depth set of nutritional info to /menu/item/{id} calls. See https://api.compassdigital.org/dev/menu/swagger.json for a list of all the possible options (that I know of)

**Comment by jonathankeebler** [comment]
Note: I left item.nutritional.kcal in the Swagger for now, but consider it deprecated
