### ISSUE TITLE
Sample items for models

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#14]
We need items with options, nutritional info, and ingredients.

**Comment by jonathankeebler** [comment]
https://api.compassdigital.org/v1/menu/swagger.json

**Comment by jonathankeebler** [comment]
We can put in sample data once we resolve #15

**Comment by jonathankeebler** [comment]
#15  is now resolved. @steve-compassdigital you can put in whatever sample data you need for testing
