### ISSUE TITLE
Missing brand description

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#18]
The location call should have a description for each brand.

This value should be visible at https://api.compassdigital.org/v1/location/616kLAy0KgFZvRNk

This value previously came from http://legacy.cafebonappetit.com/api/2/cafes?cafe=250 and we had to strip the html tags.

This value is used on the menu screen on the top of the page.

**Comment by jonathankeebler** [comment]
http://dev.cm.bamcotest.com/api/2/cafes?cafe=1600 has a description which isn't appearing in https://api.compassdigital.org/v1/location/616kLAy0KgFZvRNk
