### ISSUE TITLE
400 response

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#19]
Looking to debug this response together.

In the browser I am getting 200 with error json.
On device I am getting 400 with empty body.

Everything looks the same.
Possibly headers or something else, not sure.

**Comment by jonathankeebler** [comment]
@steve-compassdigital I need some details about what you're calling, and how to reproduce the problem

**Comment by steve-compassdigital** [comment]
Seems like this was a duplicate of the other issue but was occurring while I was debugging another bug.
