### ISSUE TITLE
Menu returning 502 frequently

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#20]
More often than not, when calling the menu, we get a 502 response code. After a few retries we will get correct response. 
Failing 3/4 times.
Reproduced in the browser at one point.

**Comment by steve-compassdigital** [comment]
This is probably not helpful since it requests the wrong Accept Header, but this is an error from the browser...

{"message": "Internal server error"}

Response Headers
X-Firefox-Spdy | h2
-- | --
content-length | 36
content-type | application/json
date | Wed, 22 Nov 2017 18:00:45 GMT
via | 1.1  af59cbeda88e3a41b2689a634f61c64d.cloudfront.net (CloudFront), 1.1  52e180bc0e5a47e4820e1923633d0ab7.cloudfront.net (CloudFront)
x-amz-cf-id | sAxnYxbj_DRle8-bamaMoG1zDkAF1TBhY6LW500cVDDR6GXePCyEkA==
x-amzn-remapped-connection | keep-alive
x-amzn-remapped-content-length | 36
x-amzn-remapped-date | Wed, 22 Nov 2017 18:00:45 GMT
x-amzn-remapped-x-amzn-requestid | 0c8cf477-cfaf-11e7-8991-ad58647c88ba
x-amzn-requestid | 0c8a8322-cfaf-11e7-820a-b9fa83112634
x-cache | Error from cloudfront

Request Headers
Accept | text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-- | --
Accept-Encoding | gzip, deflate, br
Accept-Language | en-US,en;q=0.5
Connection | keep-alive
Host | api.compassdigital.org
Upgrade-Insecure-Requests | 1
User-Agent | Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by jonathankeebler** [comment]
@steve-compassdigital What URL were you hitting?

**Comment by steve-compassdigital** [comment]
https://api.compassdigital.org/v1/menu/4Wyo3JRLMRIBm4gNrRQKt90Nag9jKKu6Kq8QZdk0Tq59er

**Comment by jonathankeebler** [comment]
@steve-compassdigital The menu 4Wyo3JRLMRIBm4gNrRQKt90Nag9jKKu6Kq8QZdk0Tq59er that you are hitting is no longer available for Grifols. See the valid menus at https://api.compassdigital.org/v1/location/616kLAy0KgFZvRNk . Just switch over to one of those, and you should be good.

I'll fix those generic 502 errors by replacing them with proper 404s.

**Comment by steve-compassdigital** [comment]
I think you're mixing up 2 different issues. There was a proper 502 coming but the server appearing to be too busy. That call would work after retrying a few times (within a few minutes).
The menu not being available today is a new issue.
1) Grifols is closed today and so all menus today were returning an error instead of the actual menu. Once Colin opened the store for today, the menu would load. The menu shouldn't be dependant on todays status since the menu was suppose to be for a different date.

**Comment by jonathankeebler** [comment]
@steve-compassdigital I created a new ticket #22 for menus not loading if the store is closed.

As for the 502s, I have detailed logs of every request coming into the server. When I look at the Wed, 22 Nov 2017 18:00:45 GMT timeframe from the headers you posted, I don't see any requests coming in for https://api.compassdigital.org/v1/menu/4Wyo3JRLMRIBm4gNrRQKt90Nag9jKKu6Kq8QZdk0Tq59er which is making it hard to debug. 

Can you reproduce the 502 right now? If so, can you get me the exact time you made the request and the URL you were hitting?

Thanks

**Comment by steve-compassdigital** [comment]
Next time I get the 502s I will post the exact time and url

**Comment by steve-compassdigital** [comment]
https://api.compassdigital.org/v1/menu/J4qRg2jwOjcAvadl7OQNuKvBzNpQOQTkmKwJXZy5COLqwD @ 14:23

**Comment by steve-compassdigital** [comment]
14:33

**Comment by steve-compassdigital** [comment]
15:28

**Comment by steve-compassdigital** [comment]
16:01

**Comment by jonathankeebler** [comment]
Thanks, I found what's going on. Working on it now

**Comment by jonathankeebler** [comment]
@steve-compassdigital We were hitting a Dynamodb rate limit that was causing the problem. I wrote some code to work around it. Eventually, I'll increase the rate limit as well, but for now I'm watching to see if the code change works. I'm running automated tests against the last URL you sent me, and I noticed the 502s disappear. Hopefully it's working for you now. If not, please reopen.
