### ISSUE TITLE
Menu and Menu/Item missing group type

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#24]
The options model needs to tell us which type of group it is.
Before we discussed about using a min and max value for number of options allowed.
For grifols and possibly bamco, I think we only would need a max value.

So "Choose 1 Cheese" would have a max of 1, and "Choose 3 Toppings" would have a max of 3. "Add your side" can have max ignored or 0, and we will allow any number of selections.

**Comment by jonathankeebler** [comment]
Resolved with addition of min/max
