### ISSUE TITLE
Server down frequently

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#30]
Server is frequently down when pulling the menu. This is impacting development for ios and android

**Comment by coho1988** [comment]
@steve-compassdigital  post url that call fails often

**Comment by steve-compassdigital** [comment]
Failed Menu
GET https://api.compassdigital.org/v1/menu/item/1BkoWK8LM8CRZQ4q6r1jIPNKR8vRzkum0D5ev35kSpaYDryBPkSEErZwrre @ 6:47 PM 09/12/2017

HTTP/1.1 400  (5912ms)
content-type: application/json; charset=utf-8
content-length: 21
date: Sat, 09 Dec 2017 23:47:02 GMT
x-amzn-requestid: 3da3716a-dd3b-11e7-bce1-ab9bd370e441
x-amzn-remapped-x-amzn-requestid: 3da6f469-dd3b-11e7-bdab-112092e5bfd9
access-control-allow-origin: *
x-amzn-remapped-content-length: 21
x-amzn-remapped-connection: keep-alive
via: 1.1 41d0ea27e141b983263dc5529dcc1ea5.cloudfront.net (CloudFront), 1.1 ecef20d250102428b019e0d560deff3c.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2c75f0-c712289254cac5c5b0dd4e75
x-amzn-remapped-date: Sat, 09 Dec 2017 23:47:02 GMT
x-cache: Error from cloudfront
x-amz-cf-id: cx6-ZOBCdbkBP9ToRjSURuuK_4Rj_SX0TyPklOu5NtfgDuUaKiIpjA==
OkHttp-Sent-Millis: 1512863215315
OkHttp-Received-Millis: 1512863221226
{"error":"Forbidden"}

**Comment by jonathankeebler** [comment]
Looking at that exact fail you left in the comments, we got a "Forbidden" error from the BAMCO api.

From our side:
```
2017-12-09T23:47:02.324Z	3da7b7dd-dd3b-11e7-9a2b-9fbe31be0c34	[SERVICE] menu : bamco provider threw an error
{
    "provider": "bamco",
    "service": "menu",
    "method": "get_menu_item",
    "error": {
        "code": -32603,
        "message": "Forbidden"
    }
}
```

**Comment by jonathankeebler** [comment]
I think this was caused by https://github.com/compassdigital/compassdigital.provider.menu.bamco/issues/46 . Health checks are at 100% right now. Please reopen this ticket if you see it happening again.
