### ISSUE TITLE
Shopping cart ignores quantity

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#31]
The quantity is ignored for the subtotal, taxes, and total.
price = 100
quantity = 3
subtotal = 100

**Comment by coho1988** [comment]
@steve-compassdigital  post example please

**Comment by steve-compassdigital** [comment]
--> POST https://api.compassdigital.org/v1/shoppingcart/ HTTP/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 98
{"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","menu":"BmBO3NG2MGId4PQW7REXsXqdmD4QlQhjdlPk59g9UZqm0Q"}
--> END POST (98-byte body)
<-- HTTP/1.1 200  (2131ms)
content-type: application/json; charset=utf-8
content-length: 257
date: Sat, 09 Dec 2017 23:50:53 GMT
x-amzn-requestid: c9eb7628-dd3b-11e7-a2f3-65bb2d3661d3
x-amzn-remapped-x-amzn-requestid: c9f6e7d0-dd3b-11e7-b27e-1f568a33ae71
access-control-allow-origin: *
x-amzn-remapped-content-length: 257
x-amzn-remapped-connection: keep-alive
via: 1.1 cbce93bae14c2990d9c172c1090b26cd.cloudfront.net (CloudFront), 1.1 52e180bc0e5a47e4820e1923633d0ab7.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2c76db-b20d8e0137196a38aa94a62e
x-amzn-remapped-date: Sat, 09 Dec 2017 23:50:53 GMT
x-cache: Miss from cloudfront
x-amz-cf-id: GX_BWnElC3qRyGpaMGe6qSTu9G19ZLXrqxn7FoM7jw3h5dIBAn-b9Q==
OkHttp-Sent-Millis: 1512863451376
OkHttp-Received-Millis: 1512863453506
{"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","menu":"BmBO3NG2MGId4PQW7REXsXqdmD4QlQhjdlPk59g9UZqm0Q","id":"JJyM1Q8L1vFlQYMlapMjfPmJgXDwRBfKBqkkrjXAse28JoZYJYSGDwNONW88TMePyM2","date":{"created":"2017-12-09T23:50:53.720Z","modified":"2017-12-09T23:50:53.720Z"}}
<-- END HTTP (257-byte body)

--> PUT https://api.compassdigital.org/v1/shoppingcart/JJyM1Q8L1vFlQYMlapMjfPmJgXDwRBfKBqkkrjXAse28JoZYJYSGDwNONW88TMePyM2 HTTP/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 443
{"items":[{"id":"1BkoWK8LM8CRZQ4q6r1jIPNKR8vRzkum0D5ev35kSpaYDryBPkSEErZwrre","options":[{"items":["a2LAdXPQgPi5gaODr4KqivaN4Bq5NQFrZNZZ78zKHW1meZe7eqFQJM7G9DBaiL0KOqEwZv"],"label":{"en":"Sides"}},{"items":["a2LAdXPQgPi5gaODr4KqivaN4Bq5NQFrZNZZ78zKHW1meZe7eqFQJM7G9DBaiL0KOqEwZv"],"label":{"en":"Sides"}},{"items":["D5BmGqQK8Qt9Wp82aKRAcqOZoLLrD2Ce6QyYvjK0T2OPPq106eCoNl62O6RYIRLO2gw"],"label":{"en":"burgers and sandwiches"}}],"quantity":2}]}
--> END PUT (443-byte body)
<-- HTTP/1.1 200  (5574ms)
content-type: application/json; charset=utf-8
content-length: 1039
date: Sat, 09 Dec 2017 23:50:59 GMT
x-amzn-requestid: cb34bf8a-dd3b-11e7-b526-95863a5c8952
x-amzn-remapped-x-amzn-requestid: cb377e46-dd3b-11e7-a982-b369c6621083
access-control-allow-origin: *
x-amzn-remapped-content-length: 1039
x-amzn-remapped-connection: keep-alive
via: 1.1 3572de112011f1b625bb77410b0c5cca.cloudfront.net (CloudFront), 1.1 52e180bc0e5a47e4820e1923633d0ab7.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2c76de-ce76bfc144249032705375f8
x-amzn-remapped-date: Sat, 09 Dec 2017 23:50:59 GMT
x-cache: Miss from cloudfront
x-amz-cf-id: FR0f-TQgLo7Mzusc_scwp_4ci9liE98GvP3WYnj5bJc_cIGq1DmQKw==
OkHttp-Sent-Millis: 1512863453532
OkHttp-Received-Millis: 1512863459105
{"menu":"BmBO3NG2MGId4PQW7REXsXqdmD4QlQhjdlPk59g9UZqm0Q","brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","date":{"created":"2017-12-09T23:50:53.720Z","modified":"2017-12-09T23:50:59.278Z"},"id":"JJyM1Q8L1vFlQYMlapMjfPmJgXDwRBfKBqkkrjXAse28JoZYJYSGDwNONW88TMePyM2","items":[{"id":"1BkoWK8LM8CRZQ4q6r1jIPNKR8vRzkum0D5ev35kSpaYDryBPkSEErZwrre","label":{"en":"House-made Black Bean Burger On Whole Grain Bun"},"description":{"en":"Black Bean, Burger, Whole Grain, Fat, Test, Flour, Water, Milk"},"nutrition":{"calories":{"amount":390,"unit":"kcal"}},"certified":{"vegetarian":true},"meta":{"orderable":true,"sub_station":"Burgers And Sandwiches"},"options":[{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"burgers and sandwiches"},"items":[],"min":0,"max":1}],"price":{"amount":4.29},"quantity":2}],"sub_total":{"amount":4.29},"taxes":{"amount":0.4},"total":{"amount":4.69}}
<-- END HTTP (1039-byte body)

**Comment by jonathankeebler** [comment]
Fixed by https://github.com/compassdigital/compassdigital.service.shoppingcart/commit/ac76be966704b3bf46c692f4a15c9fbbbd00b125
