### ISSUE TITLE
Swagger missing many objects

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#34]
Many parameters are missing in swagger. They are document as "object" but we don't have other information. "payment" and "date" of shoppingcart are examples

**Comment by jonathankeebler** [comment]
@steve-compassdigital will document specifics and they will get into the Swagger

**Comment by jonathankeebler** [comment]
@jpdemiranda I know you added a bunch of these. Are we all good now?
