### ISSUE TITLE
customer id from email to key

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#35]
DH uses customer email to identify the user. DH2 uses a different key. Where do we get the id for DH2?

**Comment by jonathankeebler** [comment]
This might not be necessary if JWT token has userid/email within it

**Comment by jonathankeebler** [comment]
@jpdemiranda is working on a solution for this

**Comment by jonathankeebler** [comment]
@jpdemiranda Can we close this issue now with the addition of the /user calls?

**Comment by jpdemiranda** [comment]
Yup!
