### ISSUE TITLE
Create Order fails because of Brand

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#38]
12-09 22:29:30.824 23976-24054/io.compassdigital.bonapp D/OkHttp: --> POST https://api.compassdigital.org/v1/order HTTP/1.1
12-09 22:29:30.824 23976-24054/io.compassdigital.bonapp D/OkHttp: Content-Type: application/json; charset=UTF-8
12-09 22:29:30.824 23976-24054/io.compassdigital.bonapp D/OkHttp: Content-Length: 536
12-09 22:29:30.824 23976-24054/io.compassdigital.bonapp D/OkHttp: {"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","customer":"fmpD2kng1pWJQMCGrLcSEg3t81rEqaSd51PMQXIuzUVT3x6u8CPZqYq_4MScjH_0JTMhI6HXIT8eBgEIhIQYVBiZuVQx_D7u2zFdQpjKT2VwQ7Z5kz8LXoeakghDEgpWZDxnzA_Ru3FCm22u1pHVkeHRcjhSOoxS_Qahmkc29IkTww9sD4tiqSr3ygB7_rPM53E5p2QiKU4WT9cGB7Y3PZEiTbWtUgzxnBGgvipDi_laMzkpVJ2fMuj4xPJLKVaXifxso6rExCmWlvAHF07dRQPaDLXyGKswS4N_ws7mXeO6qC8eqy-nSUvY_oAMlpJrugYOEgPhivW2NVO4zK2lufD3yiw","payment":"Test Payment","pickup":"Test Pickup","shoppingcart":"JJyM1Q8L1vFlQY4kDa7vTB0jX2WK97UvO2djEj4Rt3m22kzGWYTGMyKj1Zk4TMRENqy"}
12-09 22:29:30.824 23976-24054/io.compassdigital.bonapp D/OkHttp: --> END POST (536-byte body)
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: <-- HTTP/1.1 400  (318ms)
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: content-type: application/json; charset=utf-8
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: content-length: 36
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: date: Sun, 10 Dec 2017 03:29:31 GMT
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-requestid: 55a96802-dd5a-11e7-98b7-4b16a7cb9de4
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-x-amzn-requestid: 55ac9c18-dd5a-11e7-b6e5-f71c0b8153fc
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: access-control-allow-origin: *
12-09 22:29:31.143 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-content-length: 36
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-connection: keep-alive
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: via: 1.1 d1201a6f66026e2a6d778a9fd9208986.cloudfront.net (CloudFront), 1.1 fff32cafd00af15289f495f7e88493ce.cloudfront.net (CloudFront)
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-trace-id: sampled=0;root=1-5a2caa1b-958ce1e959d9210ccdea5490
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amzn-remapped-date: Sun, 10 Dec 2017 03:29:31 GMT
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: x-cache: Error from cloudfront
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: x-amz-cf-id: OooTBKs-wf3UvHlm-3iJG8Z0WDxwW2DVleZPIFXn-fcSsSdFD7rx6w==
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: OkHttp-Sent-Millis: 1512876570825
12-09 22:29:31.144 23976-24054/io.compassdigital.bonapp D/OkHttp: OkHttp-Received-Millis: 1512876571142
12-09 22:29:31.145 23976-24054/io.compassdigital.bonapp D/OkHttp: {"error":"No Location Brand passed"}
12-09 22:29:31.145 23976-24054/io.compassdigital.bonapp D/OkHttp: <-- END HTTP (36-byte body)

**Comment by steve-compassdigital** [comment]
Brand Id is passed, but error message says brand wasn't passed

**Comment by steve-compassdigital** [comment]
--> POST https://api.compassdigital.org/v1/order HTTP/1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 536
{"brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","customer":"fmpD2kng1pWJQMCGrLcSEg3t81rEqaSd51PMQXIuzUVT3x6u8CPZqYq_4MScjH_0JTMhI6HXIT8eBgEIhIQYVBiZuVQx_D7u2zFdQpjKT2VwQ7Z5kz8LXoeakghDEgpWZDxnzA_Ru3FCm22u1pHVkeHRcjhSOoxS_Qahmkc29IkTww9sD4tiqSr3ygB7_rPM53E5p2QiKU4WT9cGB7Y3PZEiTbWtUgzxnBGgvipDi_laMzkpVJ2fMuj4xPJLKVaXifxso6rExCmWlvAHF07dRQPaDLXyGKswS4N_ws7mXeO6qC8eqy-nSUvY_oAMlpJrugYOEgPhivW2NVO4zK2lufD3yiw","payment":"Test Payment","pickup":"Test Pickup","shoppingcart":"JJyM1Q8L1vFlQY4kDa7vTB0jX2WK97UvO2djEj4Rt3m22kzGWYTGMyKj1Zk4TMRENqy"}
--> END POST (536-byte body)
<-- HTTP/1.1 400  (318ms)
content-type: application/json; charset=utf-8
content-length: 36
date: Sun, 10 Dec 2017 03:29:31 GMT
x-amzn-requestid: 55a96802-dd5a-11e7-98b7-4b16a7cb9de4
x-amzn-remapped-x-amzn-requestid: 55ac9c18-dd5a-11e7-b6e5-f71c0b8153fc
access-control-allow-origin: *
x-amzn-remapped-content-length: 36
x-amzn-remapped-connection: keep-alive
via: 1.1 d1201a6f66026e2a6d778a9fd9208986.cloudfront.net (CloudFront), 1.1 fff32cafd00af15289f495f7e88493ce.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2caa1b-958ce1e959d9210ccdea5490
x-amzn-remapped-date: Sun, 10 Dec 2017 03:29:31 GMT
x-cache: Error from cloudfront
x-amz-cf-id: OooTBKs-wf3UvHlm-3iJG8Z0WDxwW2DVleZPIFXn-fcSsSdFD7rx6w==
OkHttp-Sent-Millis: 1512876570825
OkHttp-Received-Millis: 1512876571142
{"error":"No Location Brand passed"}
<-- END HTTP (36-byte body)

**Comment by steve-compassdigital** [comment]
Same log without the print timestamp

**Comment by jpdemiranda** [comment]
@steve-compassdigital Looks like you are using an old version of the swagger.  https://api.compassdigital.org/v1/order/swagger.json . The brand is now location_brand. 
Also, what are you passing as the customer?  Is that the bearer token? 
You are also not following the definition for the other properties ex. pickup should be date string and payment should have a property of card_id in it.

Here is a valid example
{
    "location_brand": "JGzRo5koArH074vMXp14UPdqoJQ7M8uGWg",
    "shoppingcart": "dXrlM0mMP1f0G98EXQkZhjZm7zEzEqIvKLjz2WOesawmrv",
    "customer": "2P2oaDOa7lt06lWoNDDjU7WQkvNBEwuPdgK7Y55zt0llD2KJOMuyNm",
    "payment": {
        "card_id": 1232123112
    },
    "is": { 
    	"accepted": true,
    	"inprogress": false,
    	"ready": false
    },
    "pickup": "2017-12-15T20:49:26.802Z",
    "pickup_name": "unit_test2"
}

**Comment by steve-compassdigital** [comment]
location_brand is no longer causing an error
