### ISSUE TITLE
Timestamps missing timezone

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#39]
Timestamps for Date are returned with 'Z' instead of timezone.
For example: "created":"2017-12-09T23:50:53.720Z"

{"menu":"BmBO3NG2MGId4PQW7REXsXqdmD4QlQhjdlPk59g9UZqm0Q","brand":"B5XY4Aq2ljsd4PYAQp70HB92M8jO0v","date":{"created":"2017-12-09T23:50:53.720Z","modified":"2017-12-09T23:50:59.278Z"},"id":"JJyM1Q8L1vFlQYMlapMjfPmJgXDwRBfKBqkkrjXAse28JoZYJYSGDwNONW88TMePyM2","items":[{"id":"1BkoWK8LM8CRZQ4q6r1jIPNKR8vRzkum0D5ev35kSpaYDryBPkSEErZwrre","label":{"en":"House-made Black Bean Burger On Whole Grain Bun"},"description":{"en":"Black Bean, Burger, Whole Grain, Fat, Test, Flour, Water, Milk"},"nutrition":{"calories":{"amount":390,"unit":"kcal"}},"certified":{"vegetarian":true},"meta":{"orderable":true,"sub_station":"Burgers And Sandwiches"},"options":[{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"Sides"},"items":[],"min":0,"max":1},{"label":{"en":"burgers and sandwiches"},"items":[],"min":0,"max":1}],"price":{"amount":4.29},"quantity":2}],"sub_total":{"amount":4.29},"taxes":{"amount":0.4},"total":{"amount":4.69}}

**Comment by jpdemiranda** [comment]
@steve-compassdigital the Z means the time is in UTC you will need to convert to the local time of the device
