### ISSUE TITLE
History has no orders

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#40]
Sample URL stopped returning results:
https://api.compassdigital.org/v1/order/customer/2P2oaDOa7lt06lWoNDDjU7WQkvNBEwuPdgK7Y55zt0llD2KJOMuyNm

--> GET https://api.compassdigital.org/v1/order/customer/2P2oaDOa7lt06lWoNDDjU7WQkvNBEwuPdgK7Y55zt0llD2KJOMuyNm HTTP/1.1
--> END GET
<-- HTTP/1.1 200  (558ms)
content-type: application/json; charset=utf-8
content-length: 13
date: Sun, 10 Dec 2017 04:37:37 GMT
x-amzn-requestid: d8d5a497-dd63-11e7-8eab-c7d46c291f32
x-amzn-remapped-x-amzn-requestid: d8db22ed-dd63-11e7-9e32-4b4218484719
access-control-allow-origin: *
x-amzn-remapped-content-length: 13
x-amzn-remapped-connection: keep-alive
via: 1.1 5fd20d9d15ca3dbd41ebba7c2495fd98.cloudfront.net (CloudFront), 1.1 52e180bc0e5a47e4820e1923633d0ab7.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2cba10-2bc4313816454c837a4af5d8
x-amzn-remapped-date: Sun, 10 Dec 2017 04:37:37 GMT
x-cache: Miss from cloudfront
x-amz-cf-id: fKK7oulXBmAeqb6JW7kjoVyOcEjKm5o4iJolCfzhXSsm5UySa6JkoA==
OkHttp-Sent-Millis: 1512880656513
OkHttp-Received-Millis: 1512880657071
{"orders":[]}
<-- END HTTP (13-byte body)

**Comment by jpdemiranda** [comment]
I'm not sure I see how this is an issue.  Have you been able to create orders?  Based on the other ticket you filed it doesn't look like you have been able to create orders yet, if there are no orders this will return an empty array.

**Comment by steve-compassdigital** [comment]
This was the sample call provided by jpdemiranda on Wed No 29 at 10:30am. It had a record showing last week and up until Friday. That record was then removed. This order should have stayed in the history as a past order. Also, as a sample for us to work with, it was provided so we would have something to develop with and now we have nothing, so we are requesting for a sample so that we can code the history section of the app while we wait on issues related to creating an order to be resolved.
