### ISSUE TITLE
Order request and response have different payments

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#43]
When creating an order, the payment card_id changes from an integer (1232123112) to a string (4POWOojoD5f27WWkgGM8FjRo6e1873Uqa7Dpvd68Ir6z)

https://api.compassdigital.org/v1/order/customer/2P2oaDOa7lt06lWoNDDjU7WQkvNBEwuPdgK7Y55zt0llD2KJOMuyNm

**Comment by jpdemiranda** [comment]
This is necessary in order to support a future card service.  Do you need the original card_id?

**Comment by steve-compassdigital** [comment]
I will need something to look up the card information or I will need the card itself returned because we display the card that was charged in the Order screen.

**Comment by steve-compassdigital** [comment]
As for the card_id, in swagger it is defined as String but you use an integer when submitting.
Which is it?
If you want it to be both, then it will have to be 2 different models. Please make swagger reflect what will be sent and received.
