### ISSUE TITLE
Timeslots returns 400 error after hours

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#44]
Swagger defines the response of https://api.compassdigital.org/v1/location/brand/B5XY4Aq2ljsd4PYAQp70HB92M8jO0v/timeslots to be 200.
 The business hours are until 5pm. After that the server returns a 400 error.

Ideally we would get a 200 with an empty array, or atleast to have the 400 in swagger so that our library can handle the error.

**Comment by steve-compassdigital** [comment]
--> GET https://api.compassdigital.org/v1/location/brand/B5XY4Aq2ljsd4PYAQp70HB92M8jO0v/timeslots HTTP/1.1
--> END GET
<-- HTTP/1.1 400  (558ms)
content-type: application/json; charset=utf-8
content-length: 62
date: Mon, 11 Dec 2017 22:06:48 GMT
x-amzn-requestid: 9530e9f1-debf-11e7-92b6-998c82681ce5
x-amzn-remapped-x-amzn-requestid: 95341e17-debf-11e7-b44b-a3b0a79201f1
access-control-allow-origin: *
x-amzn-remapped-content-length: 62
x-amzn-remapped-connection: keep-alive
via: 1.1 903af4f08e8327b236ac118f3e021063.cloudfront.net (CloudFront), 1.1 126677158516d6659a5afcc26674bdd1.cloudfront.net (CloudFront)
x-amzn-trace-id: sampled=0;root=1-5a2f0178-724cc91d364c66d4a30b6bfe
x-amzn-remapped-date: Mon, 11 Dec 2017 22:06:48 GMT
x-cache: Error from cloudfront
x-amz-cf-id: 6R-ao0udsEwI0yHHsBdw3TvOdhRfoD9FEVL2NM9eDWY5hm4jePmCOQ==
OkHttp-Sent-Millis: 1513030007203
OkHttp-Received-Millis: 1513030007760
{"error":"Could not find any open hours that match your date"}
<-- END HTTP (62-byte body)

**Comment by jonathankeebler** [comment]
@jpdemiranda I think all the piping is in there to return a non-200 response via Lambda

**Comment by steve-compassdigital** [comment]
The current method is going to be hard for Suman to code/test because when they work, it is outside of office hours...

**Comment by jpdemiranda** [comment]
I added a definition for a 400 response ... let me know if that is going to work for you.  
I think that Suman is going to have to pass in a date in order to get the timeslots.  Unless you have another suggestion of expected behaviour.

**Comment by coho1988** [comment]
@jpdemiranda  please return a empty array  and 200 response instead per meeting on 12/13/2017

**Comment by jpdemiranda** [comment]
Returning an empty array now
