### ISSUE TITLE
Response codes for failed create order

### ISSUE THREAD

**Issue by steve-compassdigital** [compassdigital/compassdigital.provider.menu.bamco#53]
There are no responses defined for failed requests to create an order.
The server will require validation for creating an order. Those validations could result in something other than a 200 response.

Currently swagger only defines the 200 response.
https://api.compassdigital.org/v1/order/swagger.json

**Comment by jonathankeebler** [comment]
Moving this to backlog since we should only be returning 200s

**Comment by jonathankeebler** [comment]
@jpdemiranda With your latest changes to Service, is this resolved?

**Comment by jpdemiranda** [comment]
@jonathankeebler the order service needs to be updated and redeployed for this to take affect and swagger needs to updated with all the possible codes

**Comment by jpdemiranda** [comment]
I'm going to add all the codes now

**Comment by jpdemiranda** [comment]
Updated error codes on v1 now
