### ISSUE TITLE
Need some sort of error code definition for different types of errors

### ISSUE THREAD

**Issue by jonathankeebler** [compassdigital/compassdigital.provider.menu.bamco#58]
For example, if we try to process a credit card order and the order fails because:
1) the credit card was expired
2) there was insufficient funds
how would we programmatically know the difference?

**Comment by jonathankeebler** [comment]
@jpdemiranda FYI you can now bubble up errors from the providers by setting the "number" attribute on the Error object you return from the handler.
Sample usage https://github.com/compassdigital/compassdigital.service/commit/5cf5eea90e066fa85410a7fd2b2ea14c74fd1870#diff-e86100b14aa4e76ebb3d84cf87feca46R197

**Comment by jpdemiranda** [comment]
cool!
