### ISSUE TITLE
improve the merchantt account so its not hardcoded. the merchant account id should be provided in the json so when the purchase is made, the mobile app will pass the merchant account when making a order

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#76]

**Comment by jpdemiranda** [comment]
The merchant id will be stored as part of the location brand in the config service.
ex
`POST https://api.compassdigital.org/dev/config/B5XY4Aq2ljsd4PYAQp70HB92M8jO0v`
`{
    "email": "kds@mailsac.com",
    "timeslots": {
        "duration": 15,
        "slots": 10
    },
    "payment": {
    	"merchant_account_id": "40971cafebonappgrifolscafe"
    }
}`
