### ISSUE TITLE
braintree credit cards not displaying correctly or being added (only 2 of them)

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#78]
take a look at the picture. 
1. when i added 0004, it should be diners club, but it showed up as discover card? 
2. i wasn't able to add maestro card 

<img width="1318" alt="screen shot 2018-01-24 at 7 36 58 pm" src="https://user-images.githubusercontent.com/30418150/35368853-77a72ab4-0153-11e8-8edd-19b2ccf2dc6a.png">

**Comment by jpdemiranda** [comment]
![image](https://user-images.githubusercontent.com/23169917/35440817-061d8768-026f-11e8-8f82-bcb4baa1f6c8.png)
Looks like Braintree lists the Diners Club card as a Discovery card internally as well.  Maybe because Diners Club is owned by Discovery.

**Comment by coho1988** [comment]
okay lets close ticket then since its accepted.
