### ISSUE TITLE
error codes incorrect based on swagger report

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#81]
1. get user auth
- invalid creational getting 503 code. swagger has shown 400.x error code

2. sign up
- same email id getting 503 code. swagger has shown 409 error code

3. forgot password
- valid user authorisation can not check getting 503. swagger has 404

**Comment by jpdemiranda** [comment]
Having commit reviewed https://github.com/compassdigital/compassdigital.service/pull/71

**Comment by jpdemiranda** [comment]
This has been pushed to v1

**Comment by coho1988** [comment]
thx @jpdemiranda  will inform Suman to verify
