### ISSUE TITLE
meta for substation displaying. should be "station" as substation was repurposed

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#82]
Ontop of displaying the sub-station, can we display the station name as well? 

![image](https://user-images.githubusercontent.com/30418150/35649897-6bb777e0-06a8-11e8-92b2-d4aca26d8de2.png)

**Comment by jonathankeebler** [comment]
@jpdemiranda Can you please mark this closed when you deploy to v1. Thanks
