### ISSUE TITLE
incorporate search names in the bamco.json

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#83]
https://bonapp.blob.core.windows.net/configs/bamco.json

incorpoate a new field under name, "search", so those are the keywords that would bring up this location.

![image](https://user-images.githubusercontent.com/30418150/35649068-e322f0dc-06a5-11e8-842c-b2abb6692bc5.png)

IE: the site location is in emeryville, but the location name is grifols. 
Only way to bring it up now is typing in EMER. if we type in GRIF it should bring it up too. 

So request. 
search: "Emeryville", "Grifols - Emeryville", "Grifols"

**Comment by jonathankeebler** [comment]
@jpdemiranda Should this take into account language?
e.g. 
``` 
{
en: "English phrase",
fr: "French phrase"
}
```
vs 
```
["English phrase", "French phrase"]

**Comment by jpdemiranda** [comment]
Actually the only config is already "en", so going to keep it consistent

**Comment by jpdemiranda** [comment]
updated https://bonapp.blob.core.windows.net/configs/bamco.json
