### ISSUE TITLE
include sides in menu call

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#89]
noticed that sides were missing. can you kindly include it? 
please see screenshot for example 

![image](https://user-images.githubusercontent.com/30418150/35935638-101428a4-0c0f-11e8-85ef-76013babb1a5.png)

**Comment by jonathankeebler** [comment]
@coho1988 Don't those come through as ingredients?

**Comment by coho1988** [comment]
nah , we did a test today, it doesnt :(

**Comment by jpdemiranda** [comment]
deployed to dev and v1
