### ISSUE TITLE
add disclaimer to bamco.json (outside the location array)

### ISSUE THREAD

**Issue by coho1988** [compassdigital/compassdigital.provider.menu.bamco#94]
“We attempt to provide nutrition information that is as complete as possible. The nutritional values are based on standard product formulations, data from our suppliers and are based on the specified portion size. Variations may occur due to the use of regional suppliers, seasonal influences, differences in product preparation at the unit level, and recipe revisions. Nutrient values are rounded according to FDA Rounding Rules. For your convenience at self-serve stations, we have provided utensils that will help you approximate the specified portion.”

**Comment by jpdemiranda** [comment]
updated https://bonapp.blob.core.windows.net/configs/bamco.json
